export { default as NotFound } from './NotFound'
export { default as Home } from './Home';
export { default as Movie } from './Movie';
export { default as MovieDetail } from './MovieDetail';
export { default as TVDetail } from './TVDetail';
export { default as Search } from './Search';
export { default as PeopleDetail } from './PeopleDetail'
export { default as PeopleMain } from './PeopleMain'
export { default as MovieNowPlaying } from './MovieNowPlaying'
export { default as MovieUpcoming } from './MovieUpComing'
export { default as MovieTopRated } from './MovieTopRated'
export { default as Tv } from './Tv'
export { default as TvAiringToday } from './TvAiringToday'
export { default as TvOnTheAir } from './TvOnTheAir'
export { default as TvTopRated } from './TvTopRated'
export { default as People } from './People'